import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router=useRouter()
  const placeOrder=()=>{
    router.push("/products")
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Hello Next JS</h1>
      </div>
      <h3>Navigation</h3>
      <div>
        <Link href="/blog">
        <h5>Blog</h5>
        </Link>
        <Link href="/products">
        <h5>Producs</h5>
        </Link>
        <Link href="/docs">
        <h5>Docs</h5>
        </Link>
        <Link href="/users">
        <h5>Users</h5>
        </Link>
      </div>
      <div>
        <button onClick={placeOrder}>Place Order</button>
      </div>
    </>
  )
}
